name: Continouos Integration

on:
  push:
    branches:
      - 'develop'
      - 'master'

  pull_request:
    branches:
      - 'develop'
      - 'master'

jobs:
  install_dependencies_and_run_test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "----------------    Entro en PR      -----------------------"
        if: github.ref == 'refs/heads/master'

      - run: echo "-----------------   Entro en un Push         -----------------------"
        if: github.event_name == 'push'

      - run: echo "---------------              Entro por ambos    -----------------------"
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'

      - run: echo ${{ github.ref }}
