name: Continouos Integration

on:
  push:
    branches:
      - 'develop'
      - 'master'

  pull_request:
    branches:
      - 'develop'
      - 'master'

jobs:
  install_dependencies_and_run_test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "----------------    Entro en PR      -----------------------"
        if: {{ github.ref == 'ref/head/master' }}

      - run: echo "-----------------   Entro en un Push         -----------------------"
        if: {{ github.event_name == 'push' }}

      - run: echo "---------------              Entro por ambos    -----------------------"
        if: {{ github.ref == 'ref/head/master' && github.event_name == 'push' }}

